add option to suppress certificate validation
dpb587/github-status-resource pull request #6
Opened 2018-01-02 14:50 UTC by ccwienk

This is relevant for "private" GitHub (enterprise) instances using self-signed certificates. An equivalent option is offered for the "official" git resource or jtarchie/pr.

2018-01-02 16:12 UTC, dpb587 requested changes
Makes sense; thoughts about updating the setting name?

2018-01-02 16:12 UTC, dpb587 commented on README.md
> + * `no_ssl_verify` - Disable certificate validation for GitHub API calls
Can this be renamed to `skip_ssl_verification` for consistency with other existing, git/non-git resource types?

2018-01-02 16:15 UTC, ccwienk commented on README.md
> + * `no_ssl_verify` - Disable certificate validation for GitHub API calls
good point - will update

2018-01-02 21:20 UTC, dpb587 approved these changes

2018-01-02 21:21 UTC, merged

2018-01-02 21:26 UTC, dpb587 commented
Merged and promoted - thanks!

2018-01-03 08:39 UTC, ccwienk commented
@dpb587 : thanks for your swift responses